name: Remote Build
on: 
  push:              # This forces it to run the moment you save the file
  workflow_dispatch: # This adds the manual button for later

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Large Source
        run: curl -L -o source.zip "https://www.filemail.com/d/sissqhlrupvreqf"

      - name: Extract Source
        run: unzip source.zip -d .

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Eaglercraft
        run: |
          chmod +x gradlew
          ./gradlew clean build

      - name: Upload HTML Result
        uses: actions/upload-artifact@v4
        with:
          name: Eaglercraft-HTML
          path: "**/build/distributions/*.zip"
